<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Policy.aspx.cs" Inherits="site.Policy" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:LinkButton ID="LinkButton1" runat="server" PostBackUrl="~/Payment.aspx">Back To Payment</asp:LinkButton>
        <br />
        <h3><asp:Label ID="termsand" runat="server" Text="Terms and Conditions and Payment Policy"></asp:Label></h3>
    
        <br />
        <h2 style="margin: 0px 0px 14px; padding: 0px 0px 7px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 19px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(255, 160, 12); background-image: url(http://www.dreamhost.com/wp-content/themes/dreamhost/images/bg-dot3.gif); background-color: rgb(255, 255, 255); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-position: 0px 100%; background-repeat: repeat no-repeat;">General Terms of Service</h2>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            WHEREAS, Hosting Web Hosting is an information provider connected to the Internet Hosting Web Hosting offers storage and transfer services over the Internet through access to its Web Server;</p>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            WHEREAS, Customer seeks to utilize Hosting Web Hosting’s server for its own purposes;</p>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            WHEREAS, the parties acknowledge that the Internet is neither owned nor controlled by any one entity; therefore, Hosting Web Hosting can make no guarantee that any given reader shall be able to access Hosting Web Hosting’s server at any given time.</p>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            Hosting Web Hosting represents that it shall make every good faith effort to ensure that its server is available as widely as possible and with as little service interruption as possible;</p>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            NOW THEREFORE, in consideration of the mutual promises contained herein, the parties agree as follows;</p>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            &nbsp;</p>
        <h2 style="margin: 0px 0px 14px; padding: 0px 0px 7px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 19px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(255, 160, 12); background-image: url(http://www.dreamhost.com/wp-content/themes/dreamhost/images/bg-dot3.gif); background-color: rgb(255, 255, 255); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-position: 0px 100%; background-repeat: repeat no-repeat;">FINANCIAL ARRANGEMENTS</h2>
        <div class="tos" style="margin: 0px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <ol style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none; list-style: decimal;">
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Customer agrees to a thirty (30) day contract minimum beginning upon commencement of service. Exact contract duration is decided upon at signup.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Customer agrees that all charges and fees associated with an account are their sole responsibility.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">There is a per-plan one time setup fee of $49.95 for all monthly shared hosting packages.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">If the customer wishes to cancel Hosting shared Web Hosting services within ninety-seven (97) days of the initial signup they shall be able to do so for any reason (aside from disablement for Terms of Service or Spam Policy violations) and have their money promptly refunded.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Services provided by 3rd parties and Hosting partners are not part of the 97-day refund policy and no early ending credit applies. Billing will stop at end of term during which the service is canceled.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">At the end of the contract term, the contract will automatically renew for the original contract length indefinitely until canceled in writing or via the web panel. After the first 97 days a canceled account will be canceled before the next payment is due and no more billing will occur nor will any payment be refunded, even for unused portions. If any non-refundable charges have already been incurred, they must be paid before the account may be cancelled.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">“97-Day Money-Back Guarantee” offer only applicable to credit card or Google Wallet payments for shared web hosting. Other forms of payment are non-refundable. Dedicated server payments are non-refundable. Domain registrations (including the value of any used free domain registrations included with the plan) are not refundable under any circumstances. SSL certificates are non-refundable. The value of any AdWords credit or other third-party add-ons is non-refundable. See domain registration agreement for more information.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Violations of Hosting’s Terms of Service, Acceptable Use Policy, or Spam Policy may, at Hosting’s discretion, result in immediate and permanent disablement without refund.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Disputed charges (“chargebacks”) associated with any Hosting account may, at Hosting’s discretion, result in immediate and permanent disablement.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Hosting will use commercially reasonable efforts to make DreamObjects available 99.9% of the time during each monthly billing cycle. If Hosting is unable to meet this service level, you will be eligible to receive a credit to apply to future DreamObjects billing cycles based upon the Unavailability for that month.<ol style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none; list-style: decimal;">
                    <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">For the purposes of this agreement, Unavailability means that either (a) the DreamObjects service is unresponsive, or (b) DreamObjects returns a server error response to valid user requests for more than 60 seconds of consecutive requests.</li>
                    <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Unavailability that is a result of scheduled maintenance is excluded from these conditions and will not be considered for service credit calculations. Scheduled maintenance is defined as maintenance that is announced at least 5 days in advance, and does not exceed one hour in any month.</li>
                    <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Service credits will be calculated as a percentage of the bill for the billing cycle that the Unavailability occurred. The percentage for the credit will be calculated by dividing the number of minutes of Unavailability by the total number of minutes in that billing cycle.</li>
                    <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Service credits must be claimed within 14 days of the Unavailability occurring by submitting a support ticket. Include as much detail as required to document the Unavailability.</li>
                    </ol>
                </li>
            </ol>
        </div>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            &nbsp;</p>
        <h2 style="margin: 0px 0px 14px; padding: 0px 0px 7px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 19px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(255, 160, 12); background-image: url(http://www.dreamhost.com/wp-content/themes/dreamhost/images/bg-dot3.gif); background-color: rgb(255, 255, 255); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-position: 0px 100%; background-repeat: repeat no-repeat;">TAXES</h2>
        <div class="tos" style="margin: 0px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <ol style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none; list-style: decimal;">
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Hosting Web Hosting shall not be liable for any taxes or other fees to be paid in accordance with or related to purchases made from Customer or Hosting Web Hosting’s server. Customer agrees to take full responsibility for all taxes and fees of any nature associated with such products sold.</li>
            </ol>
        </div>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            &nbsp;</p>
        <h2 style="margin: 0px 0px 14px; padding: 0px 0px 7px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 19px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(255, 160, 12); background-image: url(http://www.dreamhost.com/wp-content/themes/dreamhost/images/bg-dot3.gif); background-color: rgb(255, 255, 255); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-position: 0px 100%; background-repeat: repeat no-repeat;">MATERIAL PRODUCTS</h2>
        <div class="tos" style="margin: 0px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <ol style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none; list-style: decimal;">
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Customer will provide Hosting Web Hosting with material and data in a condition that is “server-ready”, which is in a form requiring no additional manipulation on the part of Hosting Web Hosting. Hosting Web Hosting shall make no effort to validate this information for content, correctness or usability.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Use of Hosting Web Hosting’s service requires a certain level of knowledge in the use of Internet languages, protocols, and software. This level of knowledge varies depending on the anticipated use and desired content of Customer’s Webspace by the Customer.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">The following examples are offered:<ol style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none; list-style: decimal;">
                    <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Web Publishing: requires a knowledge of HTML, properly locating and linking documents, FTPing Webspace contents, Graphics, text, Sound, imagemapping, etc.</li>
                    <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">CGI-Scripts: requires a knowledge of the UNIX environment, TAR &amp; GUNZIP commands, Perl, CShell scripts, permissions, etc.</li>
                    </ol>
                </li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">The Customer agrees that he or she has the necessary knowledge to create Customer’s Webspace. Customer agrees that it is not the responsibility of Hosting Web Hosting to provide this knowledge or Customer Support outside of the defined service of Hosting Web Hosting.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Hosting Web Hosting will exercise no control whatsoever over the content of the information passing through the network, provided that it adheres to all other conditions set forth in our Terms of Service and Acceptable Use Policy documents.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Hosting Web Hosting reserves the right to police its network to verify compliance with all agreed upon Terms.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">The Customer agrees to cooperate in any reasonable investigations into their adherence to all agreed upon Terms. Failure to cooperate is grounds for immediate disablement of all accounts/service plans.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Hosting Web Hosting reserves the right to disconnect any website or server deemed to present a security threat to Hosting’s customers, servers, or network.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">The opening of multiple accounts or service plans in order to bypass any restrictions or overage charges set forth by Hosting is grounds for termination of all services.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Hosting Web Hosting makes no warranties or representations of any kind, whether expressed or implied for the service it is providing. Hosting Web Hosting also disclaims any warranty of merchantability or fitness for a particular purpose and will not be responsible for any damages that may be suffered by the Customer, including loss of data resulting from delays, non-deliveries or service interruptions by any cause or errors or omissions of the Customer. Use of any information obtained by way of Hosting Web Hosting is at the Customer’s own risk, and Hosting Web Hosting specifically denies any responsibility for the accuracy or quality of information obtained through its services. Connection speed represents the speed of a connection to and do not 
                    represent guarantees of available end to end bandwidth. Hosting Web Hosting expressly limits its damages to the Customer for any non-accessibility time or other down time to the pro-rata monthly charge during the system unavailability.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Hosting Web Hosting specifically denies any responsibilities for any damages arising as a consequence of such unavailability. In the event that this material is not “Server-ready”, Hosting Web Hosting may, at its option and at any time, reject this material, including but not limited to after it has been put on Hosting Web Hosting’s Server. Hosting Web Hosting agrees to notify Customer immediately of its refusal of the material and afford Customer the opportunity to amend or modify the material to satisfy the needs and/or requirements of Hosting Web Hosting. If the Customer fails to modify the material, as directed by Hosting Web Hosting, within a reasonable period of time, which shall be determined between the parties themselves, the contract 
                    shall be deemed to be terminated.</li>
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">All domain names registered through Hosting or its previous domain registration site, domainitron.com, that are ‘parked’ or are otherwise not immediately associated with a Hosting hosting plan will be automatically pointed to a “Coming Soon” web page which informs visitors that the registrant has recently registered their domain name via Dreamhost.com. The Coming Soon web page may be modified at any time by Hosting without prior notice to you and may include such things as, without limitation, links to additional products and services offered by Hosting.</li>
            </ol>
        </div>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            &nbsp;</p>
        <h2 style="margin: 0px 0px 14px; padding: 0px 0px 7px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 19px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(255, 160, 12); background-image: url(http://www.dreamhost.com/wp-content/themes/dreamhost/images/bg-dot3.gif); background-color: rgb(255, 255, 255); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-position: 0px 100%; background-repeat: repeat no-repeat;">TRADEMARKS &amp; COPYRIGHTS</h2>
        <div class="tos" style="margin: 0px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <ol style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none; list-style: decimal;">
                <li style="margin: 0px 0px 0px 2.5em; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; vertical-align: baseline; outline: none;">Customer warrants that it has the right to use the trademarks and copyrights applicable to all content and/or products being made available through the customer’s account.</li>
            </ol>
        </div>
        <p style="margin: 0px 0px 15px; padding: 0px; border: 0px; font-family: 'Lucida Sans Unicode', 'Lucida Grande', Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; line-height: 19px; vertical-align: baseline; outline: none; color: rgb(51, 51, 51); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            &nbsp;</p>
    </div>
    </form>
</body>
</html>
